service: product-service-tatsiana-helakhava

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  profile: js-cc4
  region: eu-central-1
  iam:
    role: 
      permissionsBoundary: 'arn:aws:iam::${aws:accountId}:policy/eo_role_boundary'
      statements: 
        - Effect: 'Allow'
          Action: 
            - s3:*
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  autoswagger:
    apiType: httpApi
  tableName: products-table-tatsiana-helakhava

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: /products
          method: GET
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: /products/{productId}
          method: GET
          cors: true
  createProduct:
    handler: handler.createProduct
    events:
      - httpApi:
          path: /products
          method: POST

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
