service: product-service-tatsiana-helakhava

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  profile: js-cc4
  region: eu-central-1
  iam:
    role: arn:aws:iam::398158581759:role/BasicLambdaExecutionRole

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: /products
          method: GET
          cors: true